version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    #command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment: 
      TZ: Asia/Tokyo
    # ports:
    #   - 3000:3000
    volumes:
      - .:/myapp
      - tmp-data:/myapp/tmp
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: nginx/
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      #- /etc/letsencrypt/live/protan.site/fullchain.pem:/ssl/server.crt
      #- /etc/letsencrypt/live/protan.site/privkey.pem:/ssl/server.key
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  db-data:
  tmp-data: